// react-frontend-hooks/src/components/CreateEmployeeComponent.js
import React, { useState } from 'react'
import { Link, useNavigate  } from 'react-router-dom'
import EmployeeService from '../services/EmployeeService';

const CreateEmployeeComponent = () => {

    const [firstName, setFirstName] = useState('');
    const [lastName, setLastName] = useState('');
    const [emailId, setEmailId] = useState('');
    const navigate = useNavigate (); //In react-router-dom v6 useHistory() is replaced by useNavigate().

    const saveEmployee = (e) => {
        e.preventDefault();

        const employee = {firstName, lastName, emailId}

        //console.log(employee);
        EmployeeService.createEmployee(employee).then((responce) => {

            console.log(responce.data);
            navigate('/employees')

        }).catch(error => {
            console.log(error);
        })

    }
    /*getTitle(){
        if ('_add' === this.state.id){
            return <h3 className='text-center'>Add Employee</h3>
        }
        return <h3 className='text-center'>Update Employee</h3>
    }*/

    return (
        <div>
            <br></br>
            <div className='container'>
                <div className='row'>
                    <div className='card col-md-6 offset-md-3 offset-md-3'>
                    <h2 className='text-center'>Add Employee</h2>
                        {
                            //this.getTitle()
                        }
                        <div className='card-body'>
                            <form>
                                <div className='form-group mb-2'>
                                    <label className='form-label'> First Name: </label>
                                    <input 
                                        type= 'text'
                                        placeholder='Enter First Name'
                                        name='firstName'
                                        className='form-control'
                                        value={firstName}
                                        onChange={(e) => setFirstName(e.target.value)} />
                                </div>
                                <div className='form-group mb-2'>
                                    <label className='form-label'> Last Name: </label>
                                    <input 
                                        type= 'text'
                                        placeholder='Enter Last Name'
                                        name='lastName'
                                        className='form-control'
                                        value={lastName}
                                        onChange={(e) => setLastName(e.target.value)} />
                                </div>
                                <div className='form-group mb-2'>
                                    <label className='form-label'> Email Id: </label>
                                    <input 
                                        type= 'text'
                                        placeholder='Enter Email Id'
                                        name='emailId'
                                        className='form-control'
                                        value={emailId}
                                        onChange={(e) => setEmailId(e.target.value)} />
                                </div>
                                <button className='btn btn-success' onClick={(e) =>saveEmployee(e)}>Save</button>
                                <Link to="/employees" className='btn btn-danger' style={{marginLeft:"10px"}}>Cancel</Link>
                            </form>
                        </div>

                    </div>

                </div>

            </div>
        </div>
    );
}

export default CreateEmployeeComponent

// angular-frontend/src/app/create-employee/create-employee.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Employee } from '../employee';
import { EmployeeService } from '../employee.service';

@Component({
  selector: 'app-create-employee',
  templateUrl: './create-employee.component.html',
  styleUrls: ['./create-employee.component.css']
})
export class CreateEmployeeComponent implements OnInit {

  employee: Employee = new Employee();
  constructor(
    private employeeService: EmployeeService,
    private router: Router) { }

  ngOnInit(): void {
  }

  saveEmployee() {
    this.employeeService.createEmployee(this.employee).subscribe(data => {
      console.log(this.employee);
      this.goToEmployeeList();
    },
    error => console.log(error));
  }

  goToEmployeeList(){
    this.router.navigate(['employees']);
  }

  onSubmit() {
    this.saveEmployee();
  }

}

<div class="col-md-6 offset-md-3">
    <h3> Create Employee </h3>
    <form (ngSubmit) = "onSubmit()">

        <div class="form-group">
            <label> First Name </label>
            <input type="text" class="form-control" id="firstName"
                [(ngModel)] = "employee.firstName" name="firstName">
        </div>
        <div class="form-group">
            <label> Last Name </label>
            <input type="text" class="form-control" id="lastName"
                [(ngModel)] = "employee.lastName" name="lastName">
        </div>
        <div class="form-group">
            <label> Email </label>
            <input type="text" class="form-control" id="emailId"
                [(ngModel)] = "employee.emailId" name="emailId">
        </div>

        <button class="btn btn-success" type="submit">Submit</button>
    </form>
</div>
