// angular-frontend/src/app/update-employee/update-employee.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Employee } from '../employee';
import { EmployeeService } from '../employee.service';

@Component({
  selector: 'app-update-employee',
  templateUrl: './update-employee.component.html',
  styleUrls: ['./update-employee.component.css']
})
export class UpdateEmployeeComponent implements OnInit {

  id!: number;
  employee: Employee = new Employee();

  constructor(
    private employeeService: EmployeeService,
    private route: ActivatedRoute,
    private router: Router) { }

  ngOnInit(): void {
    this.id = this.route.snapshot.params['id'];
    this.employeeService.getEmployeeById(this.id).subscribe(data => {
      this.employee = data;
      console.log(this.employee);
    },
    error => console.log(error));
  }

  goToEmployeeList(){
    this.router.navigate(['employees']);
  }

  onSubmit() {
    // or separate this.updateEmployee();
      this.employeeService.updateEmployee(this.employee).subscribe(data => {
        console.log(this.employee);
        this.goToEmployeeList();
      },
      error => console.log(error));
  }
  
}

<div class="col-md-6 offset-md-3">
    <h3> Update Employee </h3>
    <form (ngSubmit) = "onSubmit()">

        <div class="form-group">
            <label> First Name </label>
            <input type="text" class="form-control" id="firstName"
                [(ngModel)] = "employee.firstName" name="firstName">
        </div>
        <div class="form-group">
            <label> Last Name </label>
            <input type="text" class="form-control" id="lastName"
                [(ngModel)] = "employee.lastName" name="lastName">
        </div>
        <div class="form-group">
            <label> Email </label>
            <input type="text" class="form-control" id="emailId"
                [(ngModel)] = "employee.emailId" name="emailId">
        </div>

        <button class="btn btn-success" type="submit">Update</button>
    </form>
</div>

// react-frontend/src/components/UpdateEmployeeComponent.jsx
import React, { Component } from 'react';
import EmployeeService from '../services/EmployeeService';
import { Link, useParams, useNavigate } from "react-router-dom";

class UpdateEmployeeComponentSub extends Component {
    constructor(props){
        super(props)
        this.state = {
            id: this.props.params.id,//this.props.match.params.id,
            firstName: '',
            lastName: '',
            emailId:''
        }

        this.changeFirstNameHandler = this.changeFirstNameHandler.bind(this);
        this.changeLastNameHandler = this.changeLastNameHandler.bind(this);
        this.changeEmailIdHandler = this.changeEmailIdHandler.bind(this);
        this.updateEmployee = this.updateEmployee.bind(this);
    }

    componentDidMount(){
        EmployeeService.getEmployeeById(this.state.id).then(res=>{
            let employee = res.data;
            this.setState({
                firstName: employee.firstName,
                lastName:employee.lastName,
                emailId: employee.emailId
            });
        })
    }

    changeFirstNameHandler=(event)=>{
        this.setState({firstName: event.target.value})
    }
    changeLastNameHandler=(event)=>{
        this.setState({lastName: event.target.value})
    }
    changeEmailIdHandler=(event)=>{
        this.setState({emailId: event.target.value})
    }

    updateEmployee = (e) => {
        e.preventDefault(); //using post and not updating GET in browser address bar
        let employee = {
            firstName: this.state.firstName, 
            lastName: this.state.lastName, 
            emailId: this.state.emailId,     
        };
        console.log('employee => ' + JSON.stringify(employee));


    }

    render() {
        return (
            <div>
                <h1>Employee Form</h1>
                <div className='container'>
                    <div className='row'>
                        <div className='card col-md-6 offset-md-3 offset-md-3'>
                            <h3 className='text-center'>Update Employee</h3>
                            <div className='card-body'>
                                <form>
                                    <div className='form-group'>
                                        <label> First Name: </label>
                                        <input placeholder='First Name' name='firstName' className='form-control'
                                            value={this.state.firstName} onChange={this.changeFirstNameHandler} />
                                    </div>
                                    <div className='form-group'>
                                        <label> Last Name: </label>
                                        <input placeholder='Last Name' name='lastName' className='form-control'
                                            value={this.state.lastName} onChange={this.changeLastNameHandler} />
                                    </div>
                                    <div className='form-group'>
                                        <label> Email Address: </label>
                                        <input placeholder='Email' name='emailId' className='form-control'
                                            value={this.state.emailId} onChange={this.changeEmailIdHandler} />
                                    </div>
                                    <button className='btn btn-success' onClick={this.updateEmployee}>Save</button>
                                    <Link to="/employees">
                                        <button className='btn btn-danger' style={{marginLeft:"10px"}}>Cancel</button>
                                    </Link>
                                </form>
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        );
    }
}
//workaround how to run react6 for classes from react5
//https://stackoverflow.com/questions/63786452/react-navigate-router-v6-invalid-hook-call
//https://stackoverflow.com/questions/70585815/react-this-props-match-is-undefined
function UpdateEmployeeComponent(props) {
    let navigate = useNavigate();
    const params = useParams();
    return <UpdateEmployeeComponentSub {...props} navigate={navigate} params={params} />
}

export default UpdateEmployeeComponent;
